"use client";

import { X, Sparkles, Loader2 } from "lucide-react";
import type { ReportResponse } from "@/lib/types";

interface ReportModalProps {
  open: boolean;
  loading: boolean;
  report: ReportResponse | null;
  error: string | null;
  onClose: () => void;
}

export default function ReportModal({
  open,
  loading,
  report,
  error,
  onClose,
}: ReportModalProps) {
  if (!open) return null;

  return (
    <div
      className="fixed inset-0 z-[2000] flex items-center justify-center bg-black/70 p-4 backdrop-blur-sm"
      onClick={onClose}
    >
      <div
        className="w-[min(640px,100%)] rounded-2xl border border-edge bg-surface shadow-2xl"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-center justify-between border-b border-edge px-5 py-4">
          <div className="flex items-center gap-2">
            <Sparkles size={18} className="text-accent" />
            <h2 className="text-sm font-semibold">Mayor&apos;s Report</h2>
          </div>
          <button
            onClick={onClose}
            className="rounded-lg p-1 text-gray-400 hover:bg-white/5 hover:text-white"
          >
            <X size={18} />
          </button>
        </div>

        <div className="max-h-[60vh] overflow-y-auto px-5 py-5">
          {loading && (
            <div className="flex items-center gap-3 py-10 text-gray-400">
              <Loader2 size={20} className="animate-spin text-accent" />
              Contacting AeroFlow AI…
            </div>
          )}

          {error && !loading && (
            <p className="py-6 text-sm text-critical">{error}</p>
          )}

          {report && !loading && (
            <>
              <pre className="whitespace-pre-wrap font-sans text-sm leading-relaxed text-gray-200">
                {report.report}
              </pre>
              <p className="mt-5 border-t border-edge pt-3 text-[11px] text-gray-500">
                Generated by{" "}
                <span className="text-accent">{report.model}</span> ·{" "}
                {report.source === "groq" ? "live Groq inference" : "offline fallback"}
              </p>
            </>
          )}
        </div>
      </div>
    </div>
  );
}
